import type {
  ChatMessage,
  Conversation,
  Group,
  Review,
  User,
} from "./types";
import oliveOilImg from "@/assets/products/olive-oil.jpg";
import headphonesImg from "@/assets/products/headphones.jpg";
import riceImg from "@/assets/products/rice.jpg";
import kidsClothesImg from "@/assets/products/kids-clothes.jpg";
import honeyImg from "@/assets/products/honey.jpg";

// Helpers
const daysFromNow = (d: number) =>
  new Date(Date.now() + d * 24 * 60 * 60 * 1000).toISOString();
const hoursFromNow = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: "u-consumer",
    name: "سارة أحمد",
    phone: "01012345678",
    email: "sara@example.com",
    role: "consumer",
    kycStatus: "none",
    joinedAt: daysAgo(40),
  },
  {
    id: "u-organizer-verified",
    name: "أحمد محمد",
    phone: "01098765432",
    email: "ahmed@example.com",
    role: "organizer",
    kycStatus: "approved",
    payment: {
      instapay: "01098765432",
      bankName: "البنك الأهلي المصري",
      accountNumber: "1234567890123",
      accountHolder: "Ahmed Mohamed",
    },
    rating: 9.2,
    reviewsCount: 47,
    successCount: 18,
    failedCount: 2,
    joinedAt: daysAgo(180),
  },
  {
    id: "u-organizer-pending",
    name: "منى علي",
    phone: "01155667788",
    email: "mona@example.com",
    role: "organizer",
    kycStatus: "pending",
    rating: 0,
    reviewsCount: 0,
    successCount: 0,
    failedCount: 0,
    joinedAt: daysAgo(2),
  },
  {
    id: "u-organizer-2",
    name: "كريم حسن",
    phone: "01233344455",
    email: "karim@example.com",
    role: "organizer",
    kycStatus: "approved",
    payment: {
      instapay: "01233344455",
      bankName: "بنك مصر",
      accountNumber: "9988776655443",
      accountHolder: "Karim Hassan",
    },
    rating: 8.4,
    reviewsCount: 22,
    successCount: 9,
    failedCount: 1,
    joinedAt: daysAgo(95),
  },
  {
    id: "u-other-consumer-1",
    name: "ليلى مصطفى",
    phone: "01011112222",
    email: "laila@example.com",
    role: "consumer",
    kycStatus: "none",
    joinedAt: daysAgo(20),
  },
  {
    id: "u-other-consumer-2",
    name: "محمود سيد",
    phone: "01233445566",
    email: "mahmoud@example.com",
    role: "consumer",
    kycStatus: "none",
    joinedAt: daysAgo(15),
  },
];

export const MOCK_GROUPS: Group[] = [
  {
    id: "g-1",
    organizerId: "u-organizer-verified",
    title: "زيت زيتون عضوي بكر ممتاز - 1 لتر",
    description:
      "زيت زيتون عضوي بكر ممتاز معصور على البارد، مستورد من إسبانيا. عبوة زجاجية 1 لتر. جودة عالية بسعر الجملة عند تجميع 50 طلب.",
    images: [oliveOilImg],
    groupPrice: 180,
    originalPrice: 320,
    minBuyers: 30,
    maxBuyers: 80,
    expiresAt: daysFromNow(2),
    createdAt: daysAgo(3),
    status: "active",
    payment: {
      instapay: "01098765432",
      bankName: "البنك الأهلي المصري",
      accountNumber: "1234567890123",
      accountHolder: "Ahmed Mohamed",
    },
    members: [
      { userId: "u-other-consumer-1", userName: "ليلى مصطفى", status: "approved", uploadedAt: daysAgo(2) },
      { userId: "u-other-consumer-2", userName: "محمود سيد", status: "approved", uploadedAt: daysAgo(2) },
      ...Array.from({ length: 23 }).map((_, i) => ({
        userId: `u-mock-${i}`,
        userName: `مشتري ${i + 1}`,
        status: "approved" as const,
        uploadedAt: daysAgo(1),
      })),
    ],
    category: "بقالة",
  },
  {
    id: "g-2",
    organizerId: "u-organizer-verified",
    title: "سماعات بلوتوث لاسلكية عالية الجودة",
    description: "سماعات لاسلكية ببطارية تدوم 24 ساعة، عزل ضوضاء نشط، مع علبة شحن. ضمان سنتين.",
    images: [headphonesImg],
    groupPrice: 850,
    originalPrice: 1500,
    minBuyers: 20,
    maxBuyers: 50,
    expiresAt: hoursFromNow(18),
    createdAt: daysAgo(2),
    status: "active",
    payment: {
      instapay: "01098765432",
      bankName: "البنك الأهلي المصري",
      accountNumber: "1234567890123",
      accountHolder: "Ahmed Mohamed",
    },
    members: Array.from({ length: 12 }).map((_, i) => ({
      userId: `u-mock-h-${i}`,
      userName: `مشتري ${i + 1}`,
      status: "approved" as const,
      uploadedAt: daysAgo(1),
    })),
    category: "إلكترونيات",
  },
  {
    id: "g-3",
    organizerId: "u-organizer-2",
    title: "أرز مصري درجة أولى - شيكارة 25 كجم",
    description: "أرز مصري درجة أولى من الفلاحين مباشرة. شيكارة 25 كجم. توصيل لباب البيت بعد اكتمال المجموعة.",
    images: [riceImg],
    groupPrice: 720,
    originalPrice: 950,
    minBuyers: 15,
    maxBuyers: 40,
    expiresAt: daysFromNow(5),
    createdAt: daysAgo(1),
    status: "active",
    payment: {
      instapay: "01233344455",
      bankName: "بنك مصر",
      accountNumber: "9988776655443",
      accountHolder: "Karim Hassan",
    },
    members: Array.from({ length: 8 }).map((_, i) => ({
      userId: `u-mock-r-${i}`,
      userName: `مشتري ${i + 1}`,
      status: "approved" as const,
      uploadedAt: daysAgo(1),
    })),
    category: "بقالة",
  },
  {
    id: "g-4",
    organizerId: "u-organizer-2",
    title: "ملابس أطفال قطن مصري - باكيت 5 قطع",
    description: "ملابس أطفال قطن مصري 100%، أعمار من 1-5 سنوات. باكيت متنوع 5 قطع.",
    images: [kidsClothesImg],
    groupPrice: 320,
    originalPrice: 600,
    minBuyers: 25,
    maxBuyers: 100,
    expiresAt: daysFromNow(7),
    createdAt: daysAgo(1),
    status: "active",
    payment: {
      instapay: "01233344455",
      bankName: "بنك مصر",
      accountNumber: "9988776655443",
      accountHolder: "Karim Hassan",
    },
    members: Array.from({ length: 5 }).map((_, i) => ({
      userId: `u-mock-c-${i}`,
      userName: `مشتري ${i + 1}`,
      status: "approved" as const,
      uploadedAt: daysAgo(1),
    })),
    category: "ملابس",
  },
  {
    id: "g-5",
    organizerId: "u-organizer-verified",
    title: "عسل نحل جبلي طبيعي - 1 كجم",
    description: "عسل نحل جبلي طبيعي 100% من المنحل مباشرة. عبوة 1 كجم في برطمان زجاجي.",
    images: [honeyImg],
    groupPrice: 240,
    originalPrice: 400,
    minBuyers: 20,
    maxBuyers: 60,
    expiresAt: daysAgo(1),
    createdAt: daysAgo(8),
    status: "succeeded",
    payment: {
      instapay: "01098765432",
      bankName: "البنك الأهلي المصري",
      accountNumber: "1234567890123",
      accountHolder: "Ahmed Mohamed",
    },
    members: Array.from({ length: 35 }).map((_, i) => ({
      userId: i === 0 ? "u-consumer" : `u-mock-o-${i}`,
      userName: i === 0 ? "سارة أحمد" : `مشتري ${i + 1}`,
      status: "approved" as const,
      uploadedAt: daysAgo(5),
    })),
    category: "بقالة",
  },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: "m-1",
    conversationId: "conv-g-1",
    senderId: "u-organizer-verified",
    senderName: "أحمد محمد",
    text: "أهلاً بكم في مجموعة زيت الزيتون. التوصيل بعد اكتمال 30 طلب.",
    createdAt: daysAgo(2),
  },
  {
    id: "m-2",
    conversationId: "conv-g-1",
    senderId: "u-other-consumer-1",
    senderName: "ليلى مصطفى",
    text: "متى المتوقع اكتمال المجموعة تقريباً؟",
    createdAt: daysAgo(1),
  },
  {
    id: "m-3",
    conversationId: "conv-g-1",
    senderId: "u-organizer-verified",
    senderName: "أحمد محمد",
    text: "خلال يومين بإذن الله. باقي 5 أعضاء فقط.",
    createdAt: hoursFromNow(-3),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-g-1",
    type: "group",
    groupId: "g-1",
    title: "زيت زيتون عضوي بكر ممتاز",
    participants: ["u-organizer-verified", "u-other-consumer-1", "u-other-consumer-2", "u-consumer"],
    lastMessage: MOCK_MESSAGES[2],
    unread: 1,
  },
  {
    id: "conv-g-5",
    type: "group",
    groupId: "g-5",
    title: "عسل نحل جبلي طبيعي",
    participants: ["u-organizer-verified", "u-consumer"],
    unread: 0,
  },
  {
    id: "conv-dm-ahmed",
    type: "direct",
    groupId: "g-1",
    title: "أحمد محمد",
    participants: ["u-organizer-verified", "u-consumer"],
    unread: 0,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r-1",
    organizerId: "u-organizer-verified",
    groupId: "g-5",
    reviewerId: "u-other-consumer-1",
    reviewerName: "ليلى مصطفى",
    rating: 10,
    text: "تجربة ممتازة، البائع محترم والمنتج وصل بحالة ممتازة.",
    createdAt: daysAgo(3),
  },
  {
    id: "r-2",
    organizerId: "u-organizer-verified",
    groupId: "g-5",
    reviewerId: "u-other-consumer-2",
    reviewerName: "محمود سيد",
    rating: 9,
    text: "سرعة في التوصيل وتعامل راقي.",
    createdAt: daysAgo(2),
  },
];
